model = "gpt-5.1-codex-max"
preferred_auth_method = "chatgpt"
sandbox_mode = "danger-full-access"
model_reasoning_effort = "high"
approval_policy = "never"

[features]
web_search_request = true # allow the model to request web searches
streamable_shell = true   # enable the streamable exec tool

[sandbox_workspace_write]
network_access = true

[projects."/lab/paper/stargaze"]
trust_level = "trusted"

[projects."~/.files"]
trust_level = "trusted"

[projects."/lab/paper/astronvim"]
trust_level = "trusted"

[projects."/lab/paper/finclab"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_full_access_warning = true
